name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: clericllm
  SERVICE: llm-bot
  REGION: us-central1

jobs:
  deploy:
    permissions: 
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

    - name: Deploy to cloud runn
      id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        source: 'gcr.io/cloudrun/llm-bot:latest'
      
    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}